1. Data Exploration and Cleaning
Load the dataset into a Pandas DataFrame and display the first 5 rows.
Check the shape, column names, and summary statistics of the dataset.
Identify and handle missing values (fill or drop based on the data type).
Convert Transaction_Date into datetime format and extract year, month, and day as new columns.

In [1]:
import pandas as pd

data = pd.read_csv("credit_card_transactions.csv")
data

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland
...,...,...,...,...,...,...,...,...,...,...
5495,105495,3262,2023-08-17,ATM,Apple Store,Travel,4554.82,Debit Card,Approved,South Hannahtown
5496,105496,1234,2023-08-18,POS,Uber,Travel,4118.51,Debit Card,Approved,South Courtney
5497,105497,3978,2023-08-18,Online,Apple Store,Clothing,2981.13,UPI,Approved,Rubenton
5498,105498,3082,2023-08-18,ATM,Uber,Clothing,2168.39,Debit Card,Approved,East Brianfurt
5499,105499,2271,2023-08-18,Mobile Payment,Netflix,Entertainment,1918.66,UPI,Approved,New Stephaniebury

In [2]:
# Load the dataset into a Pandas DataFrame and display the first 5 rows

data.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland

In [3]:
# Check the shape, column names, and summary statistics of the dataset

print('Shape of Data \n ',data.shape) # Row & Column
print('Column Name \n', data.columns.to_list()) #Featching Column Name
print('Summary Statistics \n ',data.describe())

# print('Summary Statistics \n ',data.describe(include='all')) #include='all' when we want summary of all column

Shape of Data
  (5500, 10)
Column Name
 ['Transaction_ID', 'Customer_ID', 'Transaction_Date', 'Transaction_Type', 'Merchant', 'Category', 'Amount', 'Payment_Mode', 'Transaction_Status', 'Location']
Summary Statistics
         Transaction_ID  Customer_ID       Amount
count     5500.000000  5500.000000  5490.000000
mean    102749.500000  2989.954182  2491.062299
std       1587.857571  1153.928878  1444.542432
min     100000.000000  1000.000000     6.550000
25%     101374.750000  1988.000000  1236.402500
50%     102749.500000  3000.000000  2502.405000
75%     104124.250000  3990.000000  3765.420000
max     105499.000000  4998.000000  4997.490000

In [4]:
data.dtypes #Checking data type

Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [5]:
# Identify and handle missing values (fill or drop based on the data type)

print(data.isnull().sum()) #Checking for Null Values

Transaction_ID         0
Customer_ID            0
Transaction_Date       0
Transaction_Type       1
Merchant               2
Category               5
Amount                10
Payment_Mode           3
Transaction_Status     2
Location               0
dtype: int64

In [6]:
# Filling missing values in Amount Column

data['Merchant'].fillna('Unknown',inplace=True)
data['Category'].fillna('Unknown',inplace=True)
data['Payment_Mode'].fillna('Unknown',inplace=True)
data['Transaction_Status'].fillna('Unknown',inplace=True)
data['Transaction_Type'].fillna('Unknown',inplace=True)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9452\434513377.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Merchant'].fillna('Unknown',inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_9452\434513377.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Category'].fillna('Unknown',inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_9452\434513377.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Payment_Mode'].fillna('Unknown',inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_9452\434513377.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Transaction_Status'].fillna('Unknown',inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_9452\434513377.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Transaction_Type'].fillna('Unknown',inplace=True)

In [10]:
# Filling missing values in Amount Column

data['Merchant'] = data['Merchant'].fillna('Unknown')
data['Category'] = data['Category'].fillna('Unknown')
data['Payment_Mode'] = data['Payment_Mode'].fillna('Unknown')
data['Transaction_Status'] = data['Transaction_Status'].fillna('Unknown')
data['Transaction_Type'] = data['Transaction_Type'].fillna('Unknown')

data['Amount'] = data['Amount'].fillna(data['Amount'].median()) #mean()

print(data.isnull().sum())
print('Data Type \n', data.dtypes)

Transaction_ID        0
Customer_ID           0
Transaction_Date      0
Transaction_Type      0
Merchant              0
Category              0
Amount                0
Payment_Mode          0
Transaction_Status    0
Location              0
dtype: int64
Data Type
 Transaction_ID          int64
Customer_ID             int64
Transaction_Date       object
Transaction_Type       object
Merchant               object
Category               object
Amount                float64
Payment_Mode           object
Transaction_Status     object
Location               object
dtype: object

In [17]:
# Convert Transaction_Date into datetime format and extract year, month, and day as new columns

data['Transaction_Date'] = pd.to_datetime(data['Transaction_Date']) #errors='coerce'

data.dtypes

Transaction_ID                 int64
Customer_ID                    int64
Transaction_Date      datetime64[ns]
Transaction_Type              object
Merchant                      object
Category                      object
Amount                       float64
Payment_Mode                  object
Transaction_Status            object
Location                      object
dtype: object

In [18]:
# extract year, month, and day as new columns

data['Year'] = data['Transaction_Date'].dt.year
data['Month'] = data['Transaction_Date'].dt.month 
data['Date'] = data['Transaction_Date'].dt.day

print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5500 entries, 0 to 5499
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction_ID      5500 non-null   int64
 1   Customer_ID         5500 non-null   int64
 2   Transaction_Date    5500 non-null   datetime64[ns]
 3   Transaction_Type    5500 non-null   object
 4   Merchant            5500 non-null   object
 5   Category            5500 non-null   object
 6   Amount              5500 non-null   float64
 7   Payment_Mode        5500 non-null   object
 8   Transaction_Status  5500 non-null   object
 9   Location            5500 non-null   object
 10  Year                5500 non-null   int32
 11  Month               5500 non-null   int32
 12  Date                5500 non-null   int32
dtypes: datetime64[ns](1), float64(1), int32(3), int64(2), object(6)
memory usage: 494.3+ KB
None

In [20]:
data.head()

,Transaction_ID,Customer_ID,Transaction_Date,Transaction_Type,Merchant,Category,Amount,Payment_Mode,Transaction_Status,Location,Year,Month,Date
0,100000,4452,2023-01-01,Online,Walmart,Travel,4520.70,Debit Card,Approved,Jonesport,2023,1,1
1,100001,2775,2023-01-01,ATM,BestBuy,Travel,1437.85,Debit Card,Approved,Port Jennifer,2023,1,1
2,100002,2259,2023-01-01,Mobile Payment,Uber,Clothing,3320.52,PayPal,Approved,Port James,2023,1,1
3,100003,4545,2023-01-01,Online,BestBuy,Travel,2659.96,Debit Card,Approved,Hawkinston,2023,1,1
4,100004,2137,2023-01-01,ATM,Amazon,Travel,2517.07,Debit Card,Approved,Matthewland,2023,1,1

In [22]:
data.to_csv("clean_data")